language: ruby
script: bin/rspec
sudo: false
cache: bundler
rvm:
  - 2.1.5
  - 2.2.4
  - 2.3.0
env:
  - FARADAY_ADAPTER=net_http
  - FARADAY_ADAPTER=em_http
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: Ri3bGJvNKfZ6ynbHcbICknWaAJFbQPlGQE9YSY9xMB7rGomsofY4yS8yf17WlSTd2MqxhzMXgbqXfkQW759Opknw75URo8tLTnSlpJsVSqV7T4dUsfNZguyQElVZMxYacFbBZEJGBdz2Ra6xbMBdg8NqVACb65I2xeK2fsvm77k=
gemfile:
  - gemfiles/Gemfile.faraday-0.8
  - Gemfile
